### ISSUE TITLE
TryWordForMatcher 

### ISSUE THREAD

**Issue by nromanen** [nromanen/Ch-045.JavaCore#12]
1.
# В Java всі методи пишуться з маленької букви.
1. Метод TryWord(String text)  що робить?
   Перевіряє, чи задовольняє даний String регулярний вираз, тому він повинен бути описаний як
   isMatches(String text, String pattern) 
2. Метод EnterNameAndOutPutName() краще переписати  в такому вигляді, щоб перед кожним введенням був вивід на консоль типу: Enter first Name, Enter Last Name, а не все  в одному рядку.

**Comment by maximenkom** [comment]
Fixed and updated.
