### ISSUE TITLE
taskCreateClassDog/Action.java

### ISSUE THREAD

**Issue by nromanen** [nromanen/Ch-045.JavaCore#9]
1. Цей метод в усіх випадках працює?
   Що з англ. мовою?
   public boolean isSaimeNaime(List<Dog> dogList) {
   
   ```
   for (int i = 0; i < dogList.size(); i++) {
       for (int j = i + 1; j < dogList.size(); j++) {
   
           if (dogList.get(i).getName().equalsIgnoreCase(dogList.get(j).getName())) {
               return true;
           }
       }
   }
   return false;
   ```
   
   }
2.  Чому в методі public Dog oldestDog(List<Dog> dogList) {
      int temp = 0;
      int temp2 = 0;
       for (int i = 0; i < dogList.size(); i++) {
       if(temp < dogList.get(i).getAge()){
           temp = dogList.get(i).getAge();
           temp2 = i;
       }
       }
       return dogList.get(temp2);
   }
   не повертати просто temp

**Comment by starovoit777** [comment]
fixed
